server/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

server/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from noviceAngler import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noviceAngler/', include('noviceAngler.urls')),
    path('common/', include('common.urls')),
]
urlpatterns += static (
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

server/noviceAngler/urls.py
from django.urls import path
from . import views

app_name = 'noviceAngler'

urlpatterns = [
  path("", views.main_page, name="main_page"),
  path("point_recommendation/", views.point_recommendation, name="point_recommendation"),
  path("point_recommendation/question/", views.point_recommendation_question, name="point_recommendation_question"),
  path("point_recommendation/result/", views.point_recommendation_result, name="point_recommendation_result"),
  path("find_fish_page/", views.find_fish_page, name="find_fish_page"),
  path("find_fish/", views.find_fish, name="find_fish"),
  path("fish_information/", views.fish_information, name="fish_information"),
  path("fish_information/<int:pk>", views.fish_information, name="fish_information"),
  # path("point_result/", views.point_result, name="point_result"),
  path('community/<int:article_id>/', views.detail, name='detail'),
  path('community/', views.community, name="community"),
  path('community/comment/create/<int:article_id>/', views.comment_create, name='comment_create'),
  path('community/article/create/', views.article_create, name="article_create"),
  path('community/article/modify/<int:article_id>/', views.article_modify, name='article_modify'),
  path('community/article/delete/<int:article_id>/', views.article_delete, name='article_delete'),
  path('community/comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
  path('community/comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

server/noviceAngler/models.py
from django.db import models
from django.contrib.auth.models import User


class Fish(models.Model):
    fish_name = models.CharField(max_length=32)
    fishing_ways = models.TextField(blank=True, null=True)
    locations = models.TextField()
    notices = models.TextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to='posts/%Y%m%d')
    season = models.CharField(max_length=32)

    def __str__(self):
        return self.fish_name


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, upload_to="", blank=True)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField()
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField()


class UserSubmission(models.Model):
    fish = models.CharField(max_length=20, blank=False)
    fishing = models.CharField(max_length=20, blank=False)
    locate = models.CharField(max_length=20, blank=False)
    hour = models.CharField(max_length=20, blank=False)
    month = models.CharField(max_length=20, blank=False)

server/noviceAngler/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['subject', 'content', 'image']
        labels = {
            'subject': '제목',
            'content': '내용', 
            'image' : '이미지',
                  }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글',
        }

server/noviceAngler/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.conf import settings
from .image_classify import load_model, image_processing, resize_image
from .models import Fish, Article, Comment, UserSubmission
from .forms import ArticleForm, CommentForm
from PIL import Image
import numpy as np
import pandas as pd
import os
import tensorflow as tf

def main_page(request, *args, **kwargs):
    return render(request, 'noviceAngler/main_page.html')

def point_recommendation(request, *args, **kwargs):
    return render(request, 'noviceAngler/point_recommendation.html')

# 낚시 포인트 추천 질문
def point_recommendation_question(request, *args, **kwargs):
    if request.method == 'POST':
        preferred_fish = request.POST.get('fish')
        preferred_fishing = request.POST.get('fishing')
        preferred_locate = request.POST.get('locate')
        preferred_hour = request.POST.get('hour')
        preferred_month = request.POST.get('month')
        
        submission = UserSubmission(fish=preferred_fish, locate=preferred_locate, fishing=preferred_fishing, hour=preferred_hour, month=preferred_month)
        submission.save()
        
        request.session['submission_id'] = submission.id
        return redirect('noviceAngler:point_recommendation_result')
    return render(request, 'noviceAngler/point_recommendation_question.html')

# 낚시 포인트 추천 코드
def find_recommendation_point(preferred_fish, preferred_fishing, preferred_locate, preferred_month, preferred_hour):
    file_path = os.path.join(settings.BASE_DIR, 'static', '포인트_추천_데이터.xlsx')
    blog_data = pd.read_excel(file_path)
    matched_points = []

    for index, row in blog_data.iterrows():
        frequency = 0
        if row['fish'] == preferred_fish:
            frequency += 1
        elif row['fishing'] == preferred_fishing:
            frequency += 1
        elif row['locate'] == preferred_locate:
            frequency += 1
        elif row['month'] == preferred_month:
            frequency += 1
        elif row['hour'] == preferred_hour:
            frequency += 1

        matched_points.append((row['point'], frequency))
    print(matched_points)

    if matched_points:
        max_frequency = max(matched_points, key=lambda x: x[1])[1]
        highest_frequency_points = [point[0] for point in matched_points if point[1] == max_frequency]

        priority = ['fish', 'locate', 'fishing', 'month', 'hour']
        recommended_point = None

        for point in highest_frequency_points:
            recommend = True
            for attr in priority:
                if row[attr] != eval(f"preferred_{attr}") and eval(f"preferred_{attr}") != '':
                    recommend = False
                    break
                if recommend:
                    recommended_point = point
                    break
        
        print(recommended_point)
        return recommended_point
    else:
        return None

# 낚시 포인트 추천 결과
def point_recommendation_result(request, *args, **kwargs):
    submission_id = request.session.get('submission_id')
    submission = UserSubmission.objects.get(id=submission_id) if submission_id else None
    fish_mapping = {
        'hairtail': '갈치',
        'mackerel': '고등어',
        'mullet': '숭어',
        'red_snapper': '참돔',
        'rockfish': '우럭',
        'flatfish': '광어',
        'no_matter': '상관없음',
    }
    locate_mapping = {
        'south_west': '남해서부',
        'south_central': '남해중부',
        'south_east': '남해동부',
        'east_south': '동해남부',
        'east_north': '동해북부',
        'west_north': '서해북부',
        'west_south': '서해남부',
        'no_matter': '상관없음',
    }
    hour_mapping = {
        '6to12': '오전6시~정오12시',
        '12to18': '정오12시~오후18시',
        '18to21': '오후18시~자정12시',
        '0to6': '자정12시~오전6시',
        'no_matter': '상관없음',
    }
    month_mapping = {
        '1': '1월',
        '2': '2월',
        '3': '3월',
        '4': '4월',
        '5': '5월',
        '6': '6월',
        '7': '7월',
        '8': '8월',
        '9': '9월',
        '10': '10월',
        '11': '11월',
        '12': '12월',
        'no_matter': '상관없음',
    }
    fishing_mapping = {
        'float': '찌낚시',
        'one-two': '원투낚시',
        'lure': '루어낚시',
        'boat': '선상낚시',
        'no_matter': '상관없음',
    }

    preferred_fish = fish_mapping.get(submission.fish, submission.fish)
    preferred_locate = locate_mapping.get(submission.locate, submission.locate)
    preferred_hour = hour_mapping.get(submission.hour, submission.hour)
    preferred_month = month_mapping.get(submission.month, submission.month)
    preferred_fishing = fishing_mapping.get(submission.fishing, submission.fishing)

    recommended_point = find_recommendation_point(preferred_fish, preferred_fishing, preferred_locate, preferred_hour, preferred_month)
    
    context = {
        'submission':submission, 
        'preferred_fish':preferred_fish,
        'preferred_locate': preferred_locate,
        'preferred_hour': preferred_hour,
        'preferred_month': preferred_month,
        'preferred_fishing': preferred_fishing,
        'recommended_point': recommended_point,
        }
    return render(request, 'noviceAngler/point_recommendation_result.html', context)

def fish_information(request, pk, *args, **kwargs):
    fish = Fish.objects.get(id=pk)
    return render(request, 'noviceAngler/fish_information.html', {'fish': fish})

def find_fish_page(request, *args, **kwargs):
    return render(request, 'noviceAngler/find_fish.html')
# def find_fish(request):
#     predicted_class = None
#     print(request.method, request.FILES['photo'])
#     if request.method == "POST" and request.FILES['photo']:
#         model = load_model()
#         uploaded_image = request.FILES['photo']
#         img = Image.open(uploaded_image)
#         img = img.resize((100, 100))
#         img = np.array(img)
#         img = img / 255.0
#         img = np.expand_dims(img, axis=0)
#         prediction = model.predict(img)
#         predicted_class_index = np.argmax(prediction)
#         fish_classes = ['갈치', '고등어', '숭어', '광어', '우럭', '참돔']
#         predicted_class = fish_classes[predicted_class_index]
#     return render(request, "noviceAngler/fish_information.html", {'fish': predicted_class})
        
def find_fish(request):
    if request.method == 'POST':
        fish = Fish.objects.get(fish_name='고등어')
        return render(request, "noviceAngler/fish_information.html", {'fish': fish})

# 게시판
def community(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    article_list = Article.objects.order_by('-create_date')
    if kw:
        article_list = article_list.filter(
            Q(subject__icontains=kw) | 
            Q(content__icontains=kw) |  
            Q(comment__content__icontains=kw) |  
            Q(author__username__icontains=kw) | 
            Q(comment__author__username__icontains=kw) 
        ).distinct()
    paginator = Paginator(article_list, 10)
    page_obj = paginator.get_page(page)
    context = {'article_list': page_obj}
    return render(request, 'noviceAngler/article_list.html', context)

# 게시물 상세
def detail(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    context = {'article': article}
    return render(request, 'noviceAngler/article_detail.html', context)

# 댓글 추가 (로그인 필요)
@login_required(login_url='common:login')
def comment_create(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.article = article
            comment.save()
            return redirect('noviceAngler:detail', article_id=article.id)
    else:
        form = CommentForm()
    context = {'article': article, 'form': form}
    return render(request, 'noviceAngler/article_detail.html', context)

# 댓글 수정 (로그인 필요)
@login_required(login_url='common:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('noviceAngler:detail', article_id=comment.article.id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('noviceAngler:detail', article_id=comment.article.id)
    else:
        form = CommentForm(instance=comment)
    context = {'comment': comment, 'form': form}
    return render(request, 'noviceAngler/comment_form.html', context)

# 댓글 삭제 (로그인 필요)
@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        comment.delete()
    return redirect('noviceAngler:detail', article_id=comment.article.id)

# 게시글 추가 (로그인 필요)
@login_required(login_url='common:login')
def article_create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.create_date = timezone.now()
            article.save()
            return redirect('noviceAngler:community')
    else:
        form = ArticleForm()
    context = {'form': form}
    return render(request, 'noviceAngler/article_form.html', context)

# 게시글 수정 (로그인 필요)
@login_required(login_url='common:login')

server/noviceAngler/templates/noviceAngler/article_detail.html
{% extends 'noviceAngler/base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 게시글 -->
    <h2 class="border-bottom py-2">{{ article.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {% if article.image %}
                <img src="{{ article.image.url }}">
                {% endif %}
                <p> {{ article.content }} </p>
            </div>
            <div class="d-flex justify-content-end">
                {% if article.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ article.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class ="mb-2">{{ article.author.username }}</div>
                    <div>{{ article.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == article.author %}
                <a href="{% url 'noviceAngler:article_modify' article.id  %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'noviceAngler:article_delete' article.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 댓글 -->
    <h5 class="border-bottom my-3 py-2">{{ article.comment_set.count }}개의 댓글이 있습니다.</h5>
    {% for comment in article.comment_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                {% if comment.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ comment.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class ="mb-2">{{ comment.author.username }}</div>
                    <div>{{ comment.create_date }}</div>
                </div>
            </div>
            <div class="my-1">
                {% if request.user == comment.author %}
                <a href="{% url 'noviceAngler:comment_modify' comment.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary " data-uri="{% url 'noviceAngler:comment_delete' comment.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'noviceAngler:comment_create' article.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류 표시 -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <div class="mb-3">
            <label for="content" class="form-label">댓글</label>
            <!-- 로그아웃 상태: 댓글 작성 금지-->
            <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

server/noviceAngler/templates/noviceAngler/article_list.html
{% extends 'noviceAngler/base.html' %}
{% load article_filter %}
{% block content %}
<div class="container my-3 overflow-auto">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'noviceAngler:article_create' %}" class="btn btn-primary">게시글 쓰기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if article_list %}
        {% for article in article_list %}
        <tr class="text-center">
            <td>
                {{ article_list.paginator.count|sub:article_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'noviceAngler:detail' article.id %}">{{ article.subject }}</a>
                {% if article.comment_set.count > 0 %}
                <span class="text-danger small mx-2">{{ article.comment_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ article.author.username }}</td>
            <td>{{ article.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">게시글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <ul class="pagination justify-content-center">
        {% if article_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ article_list.previous_page_number }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이징 처리 -->
        {% for page_number in article_list.paginator.page_range %}
        {% if page_number >= article_list.number|add:-5 and page_number <= article_list.number|add:5 %}
        {% if page_number == article_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page= "{{ page_number }}" href=="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page = "{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        {% if article_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ article_list.next_page_number }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
</div>
<form id="searchForm" method="get" action="{% url 'noviceAngler:community' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1; 
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

server/noviceAngler/templates/noviceAngler/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/base_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/main_page_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/find_fish_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/point_recommendation_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/point_recommendation_question_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/point_recommendation_result_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/fish_information_styles.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
  <title>어쩌다어부</title>
</head>
<body>
  <nav class="navbar">
    <a href="{% url 'noviceAngler:main_page' %}" class="logo">
        <img src="{% static 'images/logo_small.png' %}" alt="">
    </a>
    <div class="menu">
      <ul>
        <li><a href="{% url 'noviceAngler:point_recommendation' %}">낚시 포인트 추천</a></li>
        <li><a href="{% url 'noviceAngler:find_fish_page' %}">물고기 찾기</a></li>
        <li><a href="{% url 'noviceAngler:community' %}">커뮤니티</a></li>
        {% if user.is_authenticated %}
        <li><a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a></li>
        {% else %}
        <li><a href="{% url 'common:login' %}">로그인</a></li>
        {% endif %}
        {% if not user.is_authenticated %}
        <li><a href="{% url 'common:signup' %}">회원가입</a></li>
        {% endif %}
      </ul>
      </div>
    </nav>
    {% block content %}

    {% endblock content %}
    <footer class="footer">
      <div class="logo">
        <a href="{% url 'noviceAngler:main_page' %}">
          <img src="{% static 'images/logo_small.png' %}" alt="">
        </a>
      </div>
      <p class="footer_text">우연히 낚시를 시작하게 된 여러분을 위한 서비스</p>
    </footer>

</body>
</html>

server/noviceAngler/templates/noviceAngler/find_fish.html
{% extends 'noviceAngler/base.html' %}
{% load static %}
{% block content %}
<main class="findfish_main">
  <div class="modal">
    <div class="modal_container">
      <div class="modal_upperbar">
        <div>사진 첨부하기</div>
        <div class="close-modal">
          <i class="fas fa-times"></i>
        </div>
      </div>
      <form class="modal_content" action="{% url 'noviceAngler:find_fish' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal_buttons">
          <input class="upload-name" value="파일선택" disabled="disabled">
          <label for="file">
            <div class="button right-mg">파일 선택</div>
          </label>
          <input class="file" name="photo" type="file" id="file" accept=".jpg, .jpeg, .png">
          <div class="delete_all button right-mg">전체 삭제</div>
        </div>
        <div class="image_dragbox">
          첨부하실 파일을 추가해 주세요.
        </div>
        <div class="modal_buttons center">
          <input value="등록" type="submit" class="register button">
          <div class="delete button">취소</div>
        </div>
      </form>
    </div>
  </div>
  <div class="findfish_image">
    <img src="{% static 'images/find_fish.png' %}" alt="">
  </div>
  <div class="findfish_textbox">
    <h1 class="point_title">물고기 찾기</h1>
    <p class="point_text1">잡은 물고기 종류가 궁금할 때 찾아주세요!</p>
    <p class="point_text2">사진 검색을 통해 여러분이 잡은 물고기의 사진을 넣어주세요.</p>
    <p class="point_text2">해당 물고기가 어떤 종류인지 찾아드립니다.</p>
    <div class="button" id="open-modal">시작하기</div>
  </div>
</main>
<script>
  const modal = document.querySelector(".modal");
  const openModalBtn = document.querySelector("#open-modal");
  const closeModalBtn = document.querySelector(".close-modal");
  const deleteBtn = document.querySelector(".delete")
  // 모달창 열기
  openModalBtn.addEventListener("click", () => {
    modal.style.display = "flex";
    document.body.style.overflow = "hidden"; // 스크롤바 제거
  });
  // 모달창 닫기
  closeModalBtn.addEventListener("click", () => {
    modal.style.display = "none";
    document.body.style.overflow = "auto"; // 스크롤바 보이기
  });
  deleteBtn.addEventListener("click", () => {
    modal.style.display = "none";
    document.body.style.overflow = "auto"; // 스크롤바 보이기
  });

  //이미지 드래그 
  const dragBox = document.querySelector(".image_dragbox");
  /* 박스 안에 Drag 들어왔을 때 */
  dragBox.addEventListener('dragenter', function(e) {
    console.log('dragenter');
  });

  /* 박스 안에 Drag를 하고 있을 때 */
  dragBox.addEventListener('dragover', function(e) {
    e.preventDefault();
    console.log('dragover');

    this.style.backgroundColor = '#7B95B7';
  });

  /* 박스 밖으로 Drag가 나갈 때 */
  dragBox.addEventListener('dragleave', function(e) {
    console.log('dragleave');

    this.style.backgroundColor = 'white';
  });

  /* 박스 안에서 Drag를 Drop했을 때 */
  dragBox.addEventListener('drop', function(e) {
    e.preventDefault();

    console.log('drop');
    this.style.backgroundColor = 'white';
  });
  //
  const fileInput = document.querySelector('#file');
  const uploadName = document.querySelector('.upload-name');
  fileInput.addEventListener('change', function(e) {
  let fileName = fileInput.files[0].name;
  
  uploadName.setAttribute('value', fileName);
})

//전체 삭제 버튼
const deleteAllBtn = document.querySelector('.delete_all')
deleteAllBtn.addEventListener('click', function() {
    fileInput.value = null
    // Check if a file is selected
    if (fileInput.files.length > 0) {
      var file = fileInput.files[0];

      // Perform file upload logic here, e.g., send it to a server

      // Delete the file from the input element
      fileInput.files.remove(0);
      console.log(fileInput.files);
    }
    console.log(fileInput.value)
    uploadName.setAttribute('value', '파일선택');
  })
</script>
{% endblock %}